theme: jekyll-theme-slate
site_favicon: assets/icons/favicon.ico
title: 24 Hour Maths
description: 

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
